POST http://localhost:3333/gateways/add
Content-Type: application/json

{
   "gatewayName": "abacate",
    "gatewayAPIKey": "string",
    "gatewaySecretKey": "string"
}

###
POST http://localhost:3333/payments/create
Content-Type: application/json

{
    "cpf": "12345678909",
    "name": "Ruan Pinheiro",
    "amount": 1092
}

###
POST http://localhost:3333/users/create
Content-Type: application/json

{
    "name": "Jean",
    "surname": "Ruan Pinheiro",
    "email": "lopesjean81@gmail.com"
}

###
POST http://localhost:3333/auth/login
Content-Type: application/json

{
    "email": "lopesjean81@gmail.com"
}